### ISSUE TITLE
Add subtitles support via existing videojs-ass plugin

### ISSUE THREAD

**Issue by hrk** [nextcloud/files_videoplayer#2]
There's an existing videojs plugin which adds support for ASS/SSA subtitles.

https://github.com/SunnyLi/videojs-ass

``` javascript
videojs('player_id', {
  plugins: {
    ass: {
      src: 'subs/subtitles.ass'
    }
  }
}
```

Ideally, the implementation in nextcloud should check if there are ASS/SSA files starting w/ the same name as the video file and add the first one as in the above example.
The videojs-ass plugin doesn't support (yet) multiple subtitles, so for starters only the first matching file could be loaded.

**Comment by Instagit** [comment]
Hey hrk, sorry for the late reply.

That's a nice plugin, but I don't think including it by default is a good idea, because the use case is very specific and Video.js already has native [support for tracks](http://docs.videojs.com/docs/guides/tracks.html), although I haven't tested if it actually works with the way Video.js is implemented in Nextcloud.

This would be best solved with an extension or possibly by converting the subtitles and using the native functionality.

**Comment by hrk** [comment]
Thank you very much for your reply.

I went and looked at the WebVTT format, which is the one Video.js supports, and I'd like your input/feedback.

WebVTT format appears to be the same as the SRT format, with two small exceptions:
1. an extra header line ("WEBVTT") plus an extra empty line
2. it uses "." in place of "," to separate seconds from milliseconds.
There's an online SRT->WebVTT converter (http://www.webvtt.org/) which does a poor job (it doesn't handle multiple lines, although the format supports them).

ASS/SSA format, however, is very different and is way more powerful (text can be positioned in specific places in the screen, think about covering/translating signs or shop names in japanese movies) whereas SRT/WebVTT is a simple "captioning" system.

I guess I see two different use-cases here.

1. Using SRT files (converting them on the fly?) with the native Video.js WebVTT support.
2. Using the videjs-ass plugin to provide "rich" ASS/SSA subtitle support.

With due time, could you please provide your feedback on both use cases?

**Comment by Instagit** [comment]
No matter which approach you prefer, it should both be doable with a Nextcloud extension relatively easily. You can use this or one of the other existing Nextcloud/[ownCloud](https://apps.owncloud.com/) video player extensions as a base and work from there. That's how I started with this player, too.

The reason I don't want to include the Video.js subtitle extension by default is that we would have to provide bug fixes and support for it in the future for a feature that is only required by very few users.

**Comment by Instagit** [comment]
I'm working on a replacement for the video player that offers subtitle support and even multiple languages. (https://github.com/nextcloud/files_videoplayer/issues/20). Subtitles are probably quite some time away though, because they require general changes to the file handling for detection and loading. If anyone needs it faster, help is definitely appreciated. :wink: 

I'll close this for now, because while it doesn't have a high priority, subtitle support is on the list.

**Comment by kuazba** [comment]
Has there been any updates? Does Nextcloud video player support closed captions now?

**Comment by Instagit** [comment]
Hi kuazba,
the new version of the player does support SRT subs as you can see in this [screenshot](https://github.com/nextcloud/files_videoplayer/issues/20#issuecomment-324657379). The subs need to be in the same directory and named like

movie.mp4
movie.en.srt
movie.de.srt

 I think we aim for it to be included with Nextcloud 13.

If you want it now, you can pull the [branch](https://github.com/nextcloud/files_videoplayer/tree/mediaelement) and install it as an extension. It's already fully usable, only needs a few minor patches. If you find any issues, however, please let me know.
