### ISSUE TITLE
Playback video in external application / native default

### ISSUE THREAD

**Issue by sunjam** [nextcloud/files_videoplayer#45]
Would it be possible to have videos switch to an external player the user might have, especially [so we can watch common, unsupported video browser formats such as avi and mpeg in Issue #29](https://github.com/nextcloud/files_videoplayer/issues/29) without having to download the file first.

**Comment by Instagit** [comment]
Hi,
you can share the file and open the direct link in a video player. I just tried with mplayer and it works.

**Comment by sunjam** [comment]
Could you please add a menu option to expedite this process and allow users to more easily open unsupported files outside of Nextcloud using whatever other video application they choose.
    
[Also, is there a list of supported file formats?](https://help.nextcloud.com/t/is-there-a-list-of-media-types-supported-by-nextcloud-files-app/24088)

**Comment by Instagit** [comment]
Media file support depends directly on the browser you are using. We added some code to support formats that are normally not supported (MKV), but it doesn't work for all videos.

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

>allow users to more easily open unsupported files outside of Nextcloud using whatever other video application they choose

That's simply not possible, because there are too many combinations of video formats and video players. Video support and compatibility with a video player may also change with software updates etc.

If video streaming is your primary concern and you don't want to change your videos to a web compatible format, your best bet might be a complete home theater solution like Kodi that is specifically made for this.

**Comment by sunjam** [comment]
What we need is a list of of which video formats are supported in Nextcloud. I have no idea what those formats are.  Do any of us know what the supported formats are?

Example:  If I create a video in Mencoder right now, what formats should I choose for native Nextcloud support?

If a format is unsupported, it makes total sense that Nextcloud would attempt to open it in a compatible application rather than download it.

**Comment by Instagit** [comment]
Like I said, Nextcloud doesn't "support" video formats. It depends on the browser. The compatibility list I posted is very much up-to-date I think:

https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility

Please note that besides the format/codec, support can also depend on the encoding level and profile.

If you want the best compromise between device support, quality and file size, H.264 and AAC saved as MP4 is the best choice. Baseline profile and encoding level 3 should be good, but you better test this on the required devices. You can probably go higher.

I recommend [Handbrake](https://handbrake.fr/) if you want a graphical tool to convert the videos. It also has presets built-in.

**Comment by Instagit** [comment]
I'm closing this. If there are further questions, feel free to ask. :)
