### ISSUE TITLE
Autoplay error

### ISSUE THREAD

**Issue by rullzer** [nextcloud/files_videoplayer#59]
See: https://sentry.rullzer.com/share/issue/93b64838ee374a07a45c29b8ed4b043a/

Basically chrome doesn't allow autoplay anymore which throws exceptions.
I guess we should be good citizens and follow the new rules and don't try to do autoplay.

**Comment by Instagit** [comment]
The autoplay permissions in Chrome are based on user interaction with the site, so I think we should be fine as the user initiates the video playback with a click.

https://www.chromium.org/audio-video/autoplay

So far it still works for me and since autoplay is clearly the expected behavior here, I'd suggest that we keep it for now.

**Comment by juliushaertl** [comment]
Seems to be an issue with the public share page only, since there is no user interaction like a click to open the video, the autoplay fails.
