### ISSUE TITLE
Video doesn't scale in fullscreen (public video share)

### ISSUE THREAD

**Issue by lsde** [nextcloud/files_videoplayer#77]
### Expected behaviour
In fullscreen mode, video scales across the whole display.

### Actual behaviour
Video doesn't scale, screen is filled with black around the video content instead.

### Steps to reproduce
1. Click the fullscreen icon
2. Observe the error
3. cry

Nextcloud 15.0.0
Video player 1.4.0
Error is present in latest Chrome, latest FF, IE 11. Windows and Linux (OSX wasn't tested)
Other players based on video.js behave as expected.
screenshot : https://i.imgur.com/I7nxHDZ.png

**Comment by Instagit** [comment]
I can't reproduce this. Is there an error message in the browser console?

1. open browser development tools (CTRL+SHIFT+I)
2. go to console tab

Also, please try to reload the page without browser cache. Should happen on its own when you have the dev tools open.

**Comment by lsde** [comment]
Thanks, DevTools unfortunately don't affect the behaviour, neither FF, Chome, regardless on the OS.
This happens to all the users on our instance, including external users, which count into hundreds.

Here is a live example:
https://transfer.digilab.nfa.cz/s/3BYJJybebtegQNd

**Comment by Instagit** [comment]
I see, so it only happens on the public share page. That's a good info and I see it now. The custom video player was only added to that page in the last few updates, so there must be an error somewhere. Probably CSS that doesn't work, because the whole structure of that page is different. We'll look into it.

**Comment by lsde** [comment]
Allright, Thanks!
Sorry, originally I should've clarified that it happens only on public share link..

**Comment by Instagit** [comment]
No worries, thanks for reporting it. :)

@juliushaertl I don't know when I got time to look at this. Maybe you can find the problem faster since you did the implementation on the public share page (https://github.com/nextcloud/files_videoplayer/commit/731a2ef582a6758f4aa407b0d7d2a17feeed9155 - https://github.com/nextcloud/files_videoplayer/commit/21fc17bbcb5e0cec31194ba8292cbf788c456760).

Part of the problem is with this CSS:

````
#imgframe .video-js .vjs-tech {
    position: relative;
    width: auto;
    height: auto;
}
````
When you remove it, the video is fine in fullscreen, but the normal player is not visible.

video.js also throws an exception on the public video page.

**Comment by juliushaertl** [comment]
@Instagit I'll have a look.

**Comment by pjrobertson** [comment]
I've proposed some changes that fix this.

**Comment by lsde** [comment]
Tested, LGTM

**Comment by Bellusterra** [comment]
I'm not sure if something got added that broke this again, but there are a few issues with shared link video in fullscreen on ios mobile. using Safari and other browsers gives same result.

- vertical video when hitting the full screen arrows in bottom right corner gives this result. 

![256-456](https://user-images.githubusercontent.com/25701774/114628001-25ca5300-9cf1-11eb-9bbe-777a93c8b2e5.jpg)


- Swiping to next video overlays previous video without closing it.

![256-455](https://user-images.githubusercontent.com/25701774/114627998-2531bc80-9cf1-11eb-83f0-f6994a39bb6b.jpg)

and sometimes hitting the full screen arrows just goes to the next video/image and doesn't function at all.

**Comment by juliushaertl** [comment]
The files video player is now part of https://github.com/nextcloud/viewer so please open a new issue over there.
