### ISSUE TITLE
issue: "the video playback was aborted..."

### ISSUE THREAD

**Issue by znbn** [nextcloud/files_videoplayer#8]
I just installed Nextcloud 10 (new installation).
I have uploaded a video (first, as recorded by my Samsung S3Neo) then encoded with Avidemux with .mp4 extension in two encoding modes (h264 and ff).
Neither of these three files (about 15MB) can be viewed directly (I have to download them and view with vlc).
I got this error "the video playback was aborted due to a corruption problem or because the video used features your browser did not support" with last Firefox and a similar error with G.Chrome.
The default video "Nextcloud.mp4" works perfectly.
Any idea?

**Comment by Instagit** [comment]
Hi,
can you try to play the video file directly in the browser? "Open with..." or drag the file into the browser.

If that doesn't work, the browser doesn't support the video format and Nextcloud won't be able to play the file since it relies on browser support.

If it does work: Could you record a short video (doesn't have to show anything, just point your phone at a wall) and upload that somewhere?

**Comment by znbn** [comment]
yes, you are right... the browser (Chrome and Firefox) doesn't support the video format.
Now I have to understand wich are correct settings to encode a .mp4 file (x264).
Thankyou so much,
Giacomo

**Comment by Instagit** [comment]
You can find a list of supported formats [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility), but for MP4 it also depends on the profile being used. Baseline profile should work.

**Comment by znbn** [comment]
Ohhh, I found my mistake:
I choosed "AVI Muxer" for Output Format when saving the file. (vlc can play the file, it recognize the correct format)
I solved selecting "MP4v2 Muxer" as Output Format.

P.S.
I wonder why, but "AVI Muxer" is the default in Avidemux software :)

P.P.S.
However Avidemux is a great software!
